### ISSUE TITLE
Woes with position:absolute from Roundabout.

### ISSUE THREAD

**Issue by TXChetG** [fredleblanc/roundabout#100]
I have Roundabout loaded up into a Wordpress install. The goal is to have it so that I can flip through the posts as the carousel. Functionally speaking everything goes well. I am running into some real trouble with the positioning however. 

It appears that Roundabout apples position:absolute to the child elements to make it's job of positioning them in the carousel easier. This is all well and good, except I am running into the classic problem with absolute positioning pulling the elements out of the flow of the page, and ending up with my main body's height being short, and the elements floating above and outside of it. 

I have tried setting several layers up the parent chain to position:relative to no avail. I am honestly out of ideas. 

I am working locally, otherwise I'd provide a link for a live example. If it comes down to needing it I'll move the project to a live example. 

Thanks everyone.

My roundabout code:

``` javascript
$(document).ready(function() {
                    $('#main').roundabout({
                        childSelector:".post",
                        enableDrag: true,
                        autoplay: false,
                        duration: 1000,
                        clickToFocus: true,
                        shape: "square",
                        debug: false
                    });
                 });
```

My basic HTML structure:

``` html
<div id="content">
    <div id="inner-content">
        <div id="main">
            <article class="post">
                Wordpress Content
            </article>
            <article class="post">
                Wordpress Content
            </article>
            <article class="post">
                Wordpress Content
            </article>
        </div>
    </div>
</div>
```

Appropriate CSS:

``` css
#content {
  margin-top: 1.5em;
}
#content #inner-content {
  background-color: #FFFFFF;
  padding: 0 20px;
  position: relative;
}
#content #inner-content #main {
  margin: 25px auto;
  width: 85%;
}
#content #inner-content #main .roundabout-holder {
  list-style: none;
  padding: 0;
  margin: 0;
  height: 5em;
  width: 100%;
}
#content #inner-content #main .roundabout-moveable-item {
  height: 4em;
  width: 85%;
  cursor: pointer;
  background-color: #ccc;
  border: 1px solid #999;
  margin: 20px 0;
}
#content #inner-content #main .roundabout-in-focus {
  cursor: auto;
}
```

Why not a screen shot for good measure:
![roundaboutExample](https://f.cloud.github.com/assets/3752043/213579/3ac306d2-8394-11e2-9f8b-eeb30f03905c.jpg)
